server:
  port: 8080
  servlet:
    context-path: /vinyoung

spring:
  datasource:
    url: jdbc:mysql://cd-cdb-k0tjjfd4.sql.tencentcdb.com:61844/young?serverTimezone=JST&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: vinyoung
    password: 82632176

  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 2000ms
  cache:
    type: redis
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
custom:
  jwt:
    tokenHeader: SevenHee-Token
    expire_time: 1800000



